### PR TITLE
[dev][defimedia] ADD random article picker

### PR DESCRIPTION
**Pull request by houzyk**
1. Gets one of these sitemaps - https://defimedia.info/sitemap.xml
2. Gets random article from selected sitemap

### CODE REVIEW

**Comment by houzyk** [comment]
#2 related

**Review by Abdur-rahmaanJ — APPROVED** [review]
@houzyk Great, nice route! Else, if you can update the README, that'd be great!

**Comment by houzyk** [comment]
> @houzyk Great, nice route! Else, if you can update the README, that'd be great!

done. also added the cli command

**Review by Abdur-rahmaanJ — APPROVED** [review]

**Comment by houzyk** [comment]
ah sorry forgot to revert that import line back

**Pull request merged**
